### ISSUE TITLE
GCC 12 issues

### ISSUE THREAD

**Issue by PlasmaPower** [rocm-arch/python-pytorch-rocm#44]
I've ran into several issues attempting to build this with GCC 12:
- https://github.com/pytorch/FBGEMM/issues/1094
- https://github.com/facebookincubator/gloo/issues/332
- https://github.com/rocm-arch/rocm-arch/issues/782#issuecomment-1149982105
- https://github.com/pytorch/pytorch/issues/77646

I'm still working on getting this building but I thought I'd open an issue to track what I've ran into, as Arch ships with GCC 12 now.

Edit: it seems to build now, locally applying fixes for the above issues

**Comment by JP-Ellis** [comment]
Thanks for collecting and aggregating all this information here! I'm glad to hear that applying the fixes above allows the build to proceed. Would you consider make a PR?

If possible, I think it is preferrable to add the PR `.patch` as new sources (though sometimes this isn't possible either because the patch against master is too dissimilar to the latest release, or sometimes there isn't a patch at all). In any case, just making it clear what the patch fixes, and when it should be safe to remove each patch.

**Comment by acxz** [comment]
Due to issues with building with gcc 12, currently out PKGBUILD builds with gcc11. This is not a priority for us, until immediate upstream uses gcc12 as well: https://github.com/archlinux/svntogit-community/tree/packages/python-pytorch/trunk

I urge you to file bug reports to the archlinux package python-pytorch. We won't implement building with gcc12 before they do. As such, even though we appreciate your work here, I'll close this issue unless it pertains with errors for this PKGBUILD or feature requests for ROCM. Feature requests or generic issues should be pointed to https://bugs.archlinux.org/
